version: '3'
services:
  api:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - 9000:9000
    # volumes:
    #   - ./:/usr/src/app:ro
    # command: uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=lllsdfl4klgg5gjsg5klsdgklgjfdlsdlfsdj33dsfdsfghh59
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALGORITHM=HS256=value
    # command: alembic upgrade head

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=postgres
#     volumes:
#       - postgres-db:/var/lib/postgresql/data
# volumes:
#     postgres-db: